In [1]:
#Importing Libraries
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [2]:
#Importing Dataset
dataset = pd.read_csv('C:\\Users\\Aditya\\Desktop\\Pokemon.csv')

In [3]:
#Dataset Summary
print(dataset.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 800 entries, 0 to 799
Data columns (total 13 columns):
 #   Column      Non-Null Count  Dtype 
---  ------      --------------  ----- 
 0   #           800 non-null    int64 
 1   Name        800 non-null    object
 2   Type 1      800 non-null    object
 3   Type 2      414 non-null    object
 4   Total       800 non-null    int64 
 5   HP          800 non-null    int64 
 6   Attack      800 non-null    int64 
 7   Defense     800 non-null    int64 
 8   Sp. Atk     800 non-null    int64 
 9   Sp. Def     800 non-null    int64 
 10  Speed       800 non-null    int64 
 11  Generation  800 non-null    int64 
 12  Legendary   800 non-null    bool  
dtypes: bool(1), int64(9), object(3)
memory usage: 75.9+ KB
None


In [4]:
#Separation of features, class label
X = dataset.iloc[:,[4,5,6,7,8,9,10]].values
print(X[:5])

[[318  45  49  49  65  65  45]
 [405  60  62  63  80  80  60]
 [525  80  82  83 100 100  80]
 [625  80 100 123 122 120  80]
 [309  39  52  43  60  50  65]]


In [5]:
#Deciding predictor columm
y = dataset.iloc[:,-1].values
print(y[:5])

[False False False False False]


In [8]:
#Encoding categorical data 
from sklearn.preprocessing import LabelEncoder
labelencoder_y = LabelEncoder()
y = labelencoder_y.fit_transform(y)
print("Sample y:",y[:5])
print('0 :',labelencoder_y.classes_[0])
print('1 :',labelencoder_y.classes_[1])

Sample y: [0 0 0 0 0]
0 : False
1 : True


In [9]:
#Splitting Data into Training and Testing
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=0)

In [10]:
#Machine Classifier | Classifier : Decision tree
from sklearn.tree import DecisionTreeClassifier
classifier = DecisionTreeClassifier(criterion='entropy', min_samples_leaf=4, random_state=0)
classifier.fit(X_train, y_train)

DecisionTreeClassifier(ccp_alpha=0.0, class_weight=None, criterion='entropy',
                       max_depth=None, max_features=None, max_leaf_nodes=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=4, min_samples_split=2,
                       min_weight_fraction_leaf=0.0, presort='deprecated',
                       random_state=0, splitter='best')

In [11]:
#Predicting the Test Set Results
y_pred = classifier.predict(X_test)

In [12]:
#Confusion Matrix
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_test,y_pred)
print(cm)

[[213   4]
 [  3  20]]


In [13]:
classifier.score(X_test, y_test)

0.9708333333333333