In [1]:
#Importing Libraries
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import warnings
warnings.filterwarnings('ignore')


In [2]:
#Importing Dataset
dataset = pd.read_csv('C:\\Users\\Aditya\\Desktop\\Pokemon.csv')

In [3]:
#Dataset Summary
dataset.head()

#                   Name Type 1  Type 2  Total  HP  Attack  Defense  \
0  1              Bulbasaur  Grass  Poison    318  45      49       49   
1  2                Ivysaur  Grass  Poison    405  60      62       63   
2  3               Venusaur  Grass  Poison    525  80      82       83   
3  3  VenusaurMega Venusaur  Grass  Poison    625  80     100      123   
4  4             Charmander   Fire     NaN    309  39      52       43   

   Sp. Atk  Sp. Def  Speed  Generation  Legendary  
0       65       65     45           1      False  
1       80       80     60           1      False  
2      100      100     80           1      False  
3      122      120     80           1      False  
4       60       50     65           1      False

In [4]:
dataset.shape

(800, 13)

In [6]:
#Separation of features, class label
X = dataset.iloc[:,[4,5,6,7,8,9,10]].values
print(X[:5])

[[318  45  49  49  65  65  45]
 [405  60  62  63  80  80  60]
 [525  80  82  83 100 100  80]
 [625  80 100 123 122 120  80]
 [309  39  52  43  60  50  65]]


In [7]:
#Deciding predictor columm
y = dataset.iloc[:,-1].values
print(y[:5])

[False False False False False]


In [8]:
from sklearn.naive_bayes import GaussianNB
gnb = GaussianNB()
y_pred = gnb.fit(X,y).predict(X)

In [9]:
print("Number of errors out of total %d points : %d"
      % (X.shape[0],(y != y_pred).sum()))

Number of errors out of total 800 points : 53


In [10]:
#So, performing simple maths for calculating accuracy
accuracy = (800-53)/800
accuracy

0.93375